name: 🐞 Bug Report
description: File a bug/issue
title: "[BUG] <title>"
labels: ["Bug", "Triage"]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      1. With this config...
      1. Run '...'
      1. See error...
  validations:
    required: false
- type: dropdown
  attributes:
    label: Operating system
    description: What operating system are you using?
    options:
      - macOS
      - Linux
      - Windows
      - Other
    default: 0
  validations:
    required: true
- type: dropdown
  attributes:
    label: Browser
    description: What browser are you using?
    options:
      - Chrome
      - Brave
      - Firefox
      - Safari
      - Edge
      - Other
    default: 0
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Screenshots? Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
