name: 📝 New Task
description: Create a new task for a user story or feature
title: "[TASK] <title>"
labels: ["Task", "Triage"]
body:
- type: textarea
  attributes:
    label: Description
    description: Provide detailed information about the task.
  validations:
    required: true
- type: textarea
  attributes:
    label: Related User Stories, Features, etc
    description: |
      If this task is related to other issues, please provide the issue reference with #.
  validations:
    required: false
